spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/user-profile
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5431/user-profile
    user: admin
    password: password
  webflux:
    base-path: /api/v1
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
    operations-sorter: method
  api-docs:
    groups:
      enabled: true
    path: /swagger-doc/v3/api-docs
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,liquibase,prometheus,mappings
  endpoint:
    health:
      enabled: true
      show-details: always
    liquibase:
      enabled: true
    mappings:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    enabled: true
    sampling.probability: 1.0
