spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/user-profile
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5431/user-profile
    user: admin
    password: password
  webflux:
    base-path: /api/v1
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
    operations-sorter: method
  api-docs:
    groups:
      enabled: true
    path: /swagger-doc/v3/api-docs

